### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by dmusican** [mikehardy/thunderlink#36]
The ctrl-alt-number keyboard shortcuts seem to have stopped working for me. Thunderlink 1.2.7, Thunderbird 60.2.1, Ubuntu 18.04.1. I've verified that my window manager isn't intercepting the shortcuts by successfully getting another app to receive them. Did something change recently either in Thunderlink or in Thunderbird regarding those shortcuts?

**Comment by mikehardy** [comment]
In fact something appears to be broken - and I just reproduced it yesterday after @kgorlen reported it as a comment here https://github.com/mikehardy/thunderlink/issues/23#issuecomment-454179276 but it should be a first-class issue, yes, so thank you for logging it.

The breakage is not intentional and I am hoping to fix it today - sorry it happened

In the meantime, all the old releases are available on both add-ons main site as well as here in the releases section - I do not believe 1.2.6 had the problem but I am not 100% sure - if you could try and report back that would be useful for others https://github.com/mikehardy/thunderlink/releases

**Comment by MarioKusek** [comment]
Hi Mike,

I have looked the code and in `thunderlink-overlay.xul` are keys mapped to call `ThunderLinkChromeNS.CopyCustomTlStringToClp`. This function no longer exist it is changed to: `ThunderLinkChromeNS.ActivateCustomTlString`.

**Comment by dmusican** [comment]
Thanks, @mikehardy, for taking a look. I just rolled back to 1.2.6: yep, the keyboard shortcuts still work in 1.2.6.

**Comment by MarioKusek** [comment]
I have created fix in https://github.com/MarioKusek/thunderlink/tree/fix/shortcutfix

**Comment by mikehardy** [comment]
@MarioKusek that is great - thank you so much! Go ahead and create the PR for master. I am okay with packaging this with multi-select to get the fix out.

@dmusican thanks for checking 1.2.6 - until 1.2.8 gets approved (sometimes takes a few days) this will help me support anyone else

**Comment by mikehardy** [comment]
(and in the meantime, I need to figure out some way to make this kind of a "build break" so it can't happen again in the future - the xul <-> js connection isn't lintable I guess, but I need to investigate)

**Comment by mikehardy** [comment]
This was resolved with #37 and 1.2.8 has been tagged and submitted for review, it will be published as soon as thunderbird.net approves it

**Comment by mikehardy** [comment]
Sorry - was called away before I could post this, but anyone affected may install the release directly before it is approved. This is the exact same binary that I submitted to add-ons.thunderbird.net https://github.com/mikehardy/thunderlink/releases/download/1.2.8/thunderlink-1.2.8-tb.xpi

**Comment by mikehardy** [comment]
Apologies for the spam but this was all reported and fixed so quickly the communication timeline is compressed. They just approved it so 1.2.8 is out through official channels. That was amazingly quick.

**Comment by kgorlen** [comment]
1.2.8 fixed the ctrl-alt shortcuts on Win10, but "Copy Subject + TL to 
clipboard" is still broken.  Here are my preferences:

user_pref("extensions.thunderlink.custom-tl-string-1-title", "Copy 
thunderlink to clipboard");
user_pref("extensions.thunderlink.custom-tl-string-2", 
"<tbexe><thunderlink>");
user_pref("extensions.thunderlink.custom-tl-string-2-title", "Copy 
executable + TL to clipboard");
user_pref("extensions.thunderlink.custom-tl-string-3", 
"<subject>\n<thunderlink>");
user_pref("extensions.thunderlink.custom-tl-string-3-title", "Copy 
Subject + TL to clipboard");
user_pref("extensions.thunderlink.open-tl-behaviour", "openInNewTab");

I think I had to edit these by hand a while back to get TL to work after 
a TB update broke it and TL was no longer supported.

Thanks.

**Comment by mikehardy** [comment]
@kgorlen I want to help but I just can't reproduce the problem with `<subject>\n<thunderlink>` on my linux or windows tests. You can see the console (ctrl+shift+J in thunderbird) and how it saw the format I copied from your preference, decoded it, and then at the bottom that was me just pasting the clipboard into the window after I did a right-click and selected the message, then selected the 3rd preference. It worked with Ctrl+Alt+3 as well. ???

I want to be clear - I'm sure there is a problem somewhere I just don't know where. Maybe you could try clearing your thunderlink preferences and reconfiguring? (or just putting a fresh attempt at subject+TL in an unused slot)?

![screenshot from 2019-01-15 14-36-59](https://user-images.githubusercontent.com/782704/51205335-abbd8080-18d3-11e9-95c6-fb7f0658ee52.png)

**Comment by kgorlen** [comment]
I reverted to thunderlink-1.2.2-beta2-tb.xpi to get Ctrl+Alt+3 working 
again.

**Comment by mikehardy** [comment]
Sorry that didn't work out for you. If you try the current version again send a screenshot of the Javascript cinsile after trying your shortcut and ill take a look

**Comment by mikehardy** [comment]
Just as a note - your screenshot didn't come through, you have to upload those using github's actual web ui. However, if you look at my console screenshot, I had actually tried (what I thought was) your shortcut with `\n` in it, so I'm still confused a bit, but I'm happy you got it working enough to stay up to date on the plugin. With 1.2.9 we just hit a point where as far as I know there are no more regressions and it'll work up to Thunderbird 65 so you'll be future-proof (for a while at least)

**Comment by kgorlen** [comment]
Maybe the characters causing the problem are CR+LF, since this is on 
Windows?

**Comment by mikehardy** [comment]
> Maybe the characters causing the problem are CR+LF, since this is on Windows?

That's a good guess - I was just using '\n' and maybe '\r\n' would do it, but what I don't understand is why your preference said this when you pasted it in above:

`user_pref("extensions.thunderlink.custom-tl-string-3","<subject>\n<thunderlink>");`

...and when I literally copy/pasted your preference string into my copy it didn't work. 🤔

**Comment by kgorlen** [comment]
Using the "Enter" key in the custom setting:

<subject>
<thunderlink>

results in:

user_pref("extensions.thunderlink.custom-tl-string-3", 
"<subject>\n<thunderlink>");

in prefs.js, and that fails.

Using "\n" in the custom setting, as is now documented:

<subject>\n<thunderlink>

results in:

user_pref("extensions.thunderlink.custom-tl-string-3", 
"<subject>\\n<thunderlink>");

in prefs.js, which works.

Many thanks for maintaining this essential add-on!
